#!/bin/bash
# -----------------------------------------------------------------------------
# docker-minecraft /start script
# -----------------------------------------------------------------------------

if [ ! -f /data/minecraft_server.jar ]
then
    curl "https://launcher.mojang.com/v1/objects/0a269b5f2c5b93b1712d0f5dc43b6182b9ab254e/server.jar" -o /data/minecraft_server.jar
fi

if [ ! -f /data/eula.txt ]
then
    echo "eula=true" > /data/eula.txt
fi

cd /data/; java -Xmx2G -jar minecraft_server.jar nogui
